function require_block_sources(here, names)
%REQUIRE_BLOCK_SOURCES  Check simulink_blocks/ is complete before using it.
%
%   require_block_sources(here, {'payload_predictor'})
%
%  The build scripts read each MATLAB Function block's code from
%  simulink_blocks/*.m with fileread. If that directory is incomplete, fileread
%  throws a bare error:
%
%      Error using fileread
%      Could not open file E:\...\simulink_blocks\payload_predictor.m.
%
%  That error is correct but says nothing about WHAT TO DO. This function does.
%
%  The usual cause: the working directory was never pulled from git, or a few
%  loose .m files were copied across and the source folder was forgotten.

src = fullfile(here, 'simulink_blocks');

if exist(src, 'dir') ~= 7
    error('require_block_sources:noDir', ...
      ['simulink_blocks/ IS MISSING\n\n' ...
       '  Looked in: %s\n\n' ...
       'That directory holds the code of the MATLAB Function blocks. Without\n' ...
       'it no block can be built, and sync_eml_blocks cannot run either.\n\n' ...
       'If the working directory is a git clone:\n' ...
       '    git fetch origin claude/main-vulnerability-check-hd94m7\n' ...
       '    git checkout claude/main-vulnerability-check-hd94m7\n\n' ...
       'Otherwise copy the whole simulink_blocks/ folder from the repository\n' ...
       'into %s (copying individual .m files leaves gaps; sync_eml_blocks\n' ...
       'needs one for every MATLAB Function block in the model).'], ...
       src, here);
end

missing = {};
for i = 1:numel(names)
    if exist(fullfile(src, [names{i} '.m']), 'file') ~= 2
        missing{end+1} = [names{i} '.m']; %#ok<AGROW>
    end
end

if ~isempty(missing)
    error('require_block_sources:noFile', ...
      ['%d FILE(S) MISSING from simulink_blocks/: %s\n\n' ...
       '  Directory: %s\n\n' ...
       'The directory exists but is incomplete - individual files were probably\n' ...
       'copied across one at a time. Pull the whole branch, or regenerate from\n' ...
       'the model:\n' ...
       '    python3 tools/extract_eml.py baseline1.slx -o simulink_blocks\n' ...
       '(that only works for blocks the .slx already contains; a NEW block has\n' ...
       ' to come from the repository, because the model has never held it.)'], ...
       numel(missing), strjoin(missing, ', '), src);
end
end
