#!/usr/bin/env python3
"""make_workflow.py - write .github/workflows/final.yml from rerun/rerun_steps.m (one job per step part).

    python rerun/make_workflow.py           # rewrite the workflow
    python rerun/make_workflow.py --check   # exit 1 if the workflow is out of date

Waves A..F run one after another (each needs the previous one; `if: always()` so a failed part does not stop the
independent steps of later waves - a step whose source is missing stops on its own assert). Within a wave every
part is its own job (GitHub: at most 20 at a time, the rest queue).
"""
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
STEPS = ROOT / "rerun" / "rerun_steps.m"
OUT = ROOT / ".github" / "workflows" / "final.yml"

HEAD = """name: final run (MATLAB, parallel)

# GENERATED by rerun/make_workflow.py from rerun/rerun_steps.m - do not edit by hand.
# The final run of the paper (docs/REGISTER_FINAL.md): wind data rebuilt from NREL M5, then waves A..F of
# rerun_steps on GitHub-hosted runners (MATLAB R2022b + Simulink, Ubuntu 22.04), one job per step part, then a
# report job that merges every part and uploads all result files (artifact "final-results").
# Manual start: GitHub -> Actions -> "final run (MATLAB, parallel)" -> Run workflow, or `gh workflow run final.yml`.

on:
  workflow_dispatch:

jobs:
  prep:
    runs-on: ubuntu-22.04
    timeout-minutes: 300
    steps:
      - uses: actions/checkout@v4
      - name: cache the exported wind segments
        id: wind
        uses: actions/cache@v4
        with:
          path: |
            wind_real_t150_i*.mat
            wind_real_t150_batch.json
            wind_expl_t150_i*.mat
            wind_expl_t150_batch.json
            wind_conf2/
            wind_sn010/
            wind_spk/
          key: wind-${{ hashFiles('rerun/m5_*.txt', 'rerun/subset_*.txt', 'rerun/prep_data.sh', 'python/export_wind_sim.py', 'python/wind/*.py', 'python/alpha_report.py', 'python/train_moe.py', 'w4_frozen_20hz_t150_train2345_s0.*') }}
      - uses: actions/setup-python@v5
        if: steps.wind.outputs.cache-hit != 'true'
        with:
          python-version: "3.13"
      - name: python packages
        if: steps.wind.outputs.cache-hit != 'true'
        run: |
          python -m pip install --upgrade pip
          python -m pip install numpy scipy
          python -m pip install torch --index-url https://download.pytorch.org/whl/cpu
          python -c "import numpy, scipy, torch; print('numpy', numpy.__version__, 'scipy', scipy.__version__, 'torch', torch.__version__)"
      - name: cache M5 raw files
        if: steps.wind.outputs.cache-hit != 'true'
        uses: actions/cache@v4
        with:
          path: m5/dev
          key: m5-dev-${{ hashFiles('rerun/m5_dev_urls.txt') }}
      - name: download M5 and export the wind segments
        if: steps.wind.outputs.cache-hit != 'true'
        run: PY=python bash rerun/prep_data.sh
      - uses: actions/upload-artifact@v4
        with:
          name: wind
          retention-days: 30
          compression-level: 1
          path: |
            wind_real_t150_i*.mat
            wind_real_t150_batch.json
            wind_expl_t150_i*.mat
            wind_expl_t150_batch.json
            wind_conf2/
            wind_sn010/
            wind_spk/
"""

WAVE = """
  wave-{w}:
    needs: {needs}
    if: always()
    strategy:
      fail-fast: false
      matrix:
        id: [{ids}]
    uses: ./.github/workflows/final-step.yml
    with:
      id: ${{{{ matrix.id }}}}
"""

TAIL = """
  report:
    needs: wave-{last}
    if: always()
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: matlab-actions/setup-matlab@v2
        with:
          release: R2022b
          products: Simulink
          cache: true
      - uses: actions/download-artifact@v4
        with:
          pattern: results-*
          path: results
          merge-multiple: true
      - uses: actions/download-artifact@v4
        with:
          pattern: log-*
          path: logs
          merge-multiple: true
      - name: merge the parts
        uses: matlab-actions/run-command@v2
        with:
          command: addpath('rerun'); setup_path; rerun_merge(); rerun_summary()
      - uses: actions/upload-artifact@v4
        with:
          name: final-results
          retention-days: 90
          path: |
            results/
            logs/
"""


def steps():
    rows = re.findall(r"^\s*'([^']+)',\s*'([A-F])',\s*(\d+),\s*@\(sh\)", STEPS.read_text(encoding="utf-8"), re.M)
    if not rows:
        raise SystemExit("no step rows found in rerun_steps.m")
    return [(i, w, int(n)) for i, w, n in rows]


def build():
    S = steps()
    waves = sorted({w for _, w, _ in S})
    out = HEAD
    prev = "prep"
    for w in waves:
        ids = []
        for i, ww, n in S:
            if ww != w:
                continue
            ids += [i] if n == 1 else [f"{i}#{k}/{n}" for k in range(1, n + 1)]
        out += WAVE.format(w=w, needs=prev, ids=", ".join(f"'{x}'" for x in ids))
        prev = f"wave-{w}"
    out += TAIL.format(last=waves[-1])
    return out, S


def main():
    text, S = build()
    njobs = sum(n for _, _, n in S)
    if "--check" in sys.argv:
        ok = OUT.exists() and OUT.read_text(encoding="utf-8") == text
        print(f"final.yml {'up to date' if ok else 'OUT OF DATE'} ({len(S)} steps, {njobs} jobs)")
        sys.exit(0 if ok else 1)
    OUT.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {OUT.relative_to(ROOT)}: {len(S)} steps, {njobs} jobs")


if __name__ == "__main__":
    main()
