#!/usr/bin/env python3
"""
build_tex.py - the IJDC submission (Springer Nature sn-jnl template) GENERATED from paper/manuscript.md.

    python paper/ijdc/build_tex.py        # writes paper/ijdc/manuscript.tex (anonymised) and copies references.bib

Do not edit manuscript.tex by hand: edit paper/manuscript.md (the single source that the gates check) and re-run.
Tables 1-5 are taken from paper/tables/tables_p2.md (generated by make_p2_tables), Table 6 from docs/RESULTS_FINAL.md
and docs/RESULTS_P2.md (generated); figures are the generated PDFs of paper/figures/. Only the labels of the tables
are rewritten here (the repository's set and claim codes -> the wording of the paper); every number is copied. The
title page with the authors and the declarations is paper/ijdc/title_page.tex (written by hand, not anonymised).

Conversion: display equations {#eq:x} -> equation + \\label, (@eq:x) -> \\eqref; pandoc (markdown -> LaTeX, natbib
citations -> \\cite); numbered headings -> \\section / \\subsection, "Section 4.5" / "Table 3" / "Fig. 2" -> \\ref;
Propositions and proofs -> proposition / proof environments; each figure and table placed after the paragraph that
first cites it; the pipe tables of the text (notation, controller list, registered predictions, Appendix A) as
unnumbered tabulars; Unicode symbols that pdflatex does not map -> LaTeX commands.
"""
import pathlib
import re
import shutil
import subprocess

ROOT = pathlib.Path(__file__).resolve().parents[2]
OUT = ROOT / "paper" / "ijdc"
MAN = ROOT / "paper" / "manuscript.md"
TAB = ROOT / "paper" / "tables" / "tables_p2.md"
RESF = ROOT / "docs" / "RESULTS_FINAL.md"
RESP = ROOT / "docs" / "RESULTS_P2.md"
TABLABEL = {1: "tab:param", 2: "tab:main", 3: "tab:ablation", 4: "tab:claims", 5: "tab:sens", 6: "tab:c2"}


def pandoc_bin():
    try:
        import pypandoc
        return pypandoc.get_pandoc_path()
    except Exception:
        return "pandoc"


def pandoc(md):
    r = subprocess.run([pandoc_bin(), "-f", "markdown-implicit_figures-fancy_lists", "-t", "latex", "--natbib", "--wrap=none"],
                       input=md.encode("utf-8"), capture_output=True)
    if r.returncode != 0:
        raise SystemExit(r.stderr.decode("utf-8", "replace"))
    return r.stdout.decode("utf-8").replace("\r\n", "\n")   # pandoc on Windows writes CRLF


UNI = {"−": r"\textminus{}", "°": r"\textdegree{}", "±": r"$\pm$", "²": r"$^2$", "×": r"$\times$", "≤": r"$\le$",
       "≥": r"$\ge$", "√": r"$\surd$", "…": r"\ldots{}", "→": r"$\rightarrow$", "≈": r"$\approx$", "–": "--"}


def unicode_fix(t):
    for k, v in UNI.items():
        t = t.replace(k, v)
    return t


# ---------------------------------------------------------------- tables from the generated sources
def esc(c):
    """A generated cell -> LaTeX text: escapes, minus signs, '-' for 'not applicable'."""
    if c.strip() in ("-", "NaN"):
        return "--"
    c = c.replace("%", r"\%").replace("_", r"\_").replace("&", r"\&").replace("NaN", "--")
    c = re.sub(r"(?<![\w.])-(?=\d)", lambda m: "$-$", c)
    c = re.sub(r"(?<= )-(?= )", lambda m: "$-$", c)
    return unicode_fix(c)


def lookup(d, c, what):
    if c not in d:
        raise SystemExit(f"build_tex: no paper wording for {what} {c!r} - add it to the map")
    return d[c]


# Table 1: quantity labels and sources of tables_p2 Table 1 -> paper wording (the values are copied)
T1_LABEL = {
    "quadrotor mass m_Q": "quadrotor mass $m_Q$",
    "payload mass m_p": "payload mass $m_p$",
    "cable length L": "cable length $L$",
    "payload damping zeta_s": "cable damping ratio $\\zeta_s$",
    "payload drag ratio K = (C_D A)_L / (C_D A)_Q": "payload drag-area ratio $K = (C_DA)_L/(C_DA)_Q$",
    "wind-force gain K_w": "wind-force gain $K_w$",
    "motor lag tau_m": "motor lag $\\tau_m$",
    "rotor force limit f_max": "rotor force limit $f_{\\max}$",
    "total thrust limit F_TOT_MAX": "total thrust limit",
    "torque limit TAU_MAX": "torque limit",
    "tilt clamp": "tilt clamp",
    "position loop / mocap": "position loop / motion capture",
    "attitude loop / IMU": "attitude loop / IMU",
    "wind sensor": "wind sensor",
    "K_gamma (position)": "$\\boldsymbol K_\\gamma$ (position)",
    "K_nu (velocity)": "$\\boldsymbol K_v$ (velocity)",
    "K_eta / K_omega (attitude)": "$\\boldsymbol K_\\eta$ / $\\boldsymbol K_\\omega$ (attitude)",
    "attitude ESO Ka1 / Ka2 / Ka3": "attitude ESO $K_{a1}$ / $K_{a2}$ / $K_{a3}$",
    "payload prediction horizon tau*": "payload-prediction horizon $\\tau$",
    "reference preview tau_prev*": "reference-preview horizon $\\tau_{prev}$",
    "PAW-MOBADC payload-wind feed-forward factor 1 + K-hat": "PAW-MOBADC feed-forward factor $1+\\hat K$",
    "INDI-type filter cut-off omega_f": "INDI-DE filter cut-off $\\omega_f$",
}
T1_VALUE = [(r" \(D1; stress 25, 30 ms\)", " (stress test 25, 30 ms)"), (r" \(N0P, sec 7\.1\)", ""),
            (r" \(sec 7\.1\)", ""), (r" \(D\d+\)", ""), (r"sigma 0 in every run", "noise-free"),
            (r"sigma 0\.2 mm", "noise SD 0.2 mm")]
T1_TEX = [("(m/s^2)/sqrt(Hz)", "(m/s$^2$)/$\\sqrt{\\mathrm{Hz}}$"), ("(rad/s)/sqrt(Hz)", "(rad/s)/$\\sqrt{\\mathrm{Hz}}$"),
          ("U\\_ref", "$U_{ref}$"), (" deg", "\\textdegree{}"), ("(x I3)", "($\\times\\boldsymbol I_3$)"),
          ("K-hat = K = 0.5", "$\\hat K = K = 0.5$")]


def t1_source(s):
    if s.startswith("[PAPER] Guo 2020"):
        return "Guo et al. \\cite{guo2020}"
    if s == "[DERIVED]":
        return "derived (Section~\\ref{sec:wind-and-the-two-disturbance-paths})"
    if "measured on dev" in s:
        return "measured, development set"
    if "assumption" in s:
        return "this work (assumed)"
    if s.startswith("[THIS WORK]"):
        return "this work"
    raise SystemExit(f"build_tex: no paper wording for the Table 1 source {s!r}")


def t1_value(v):
    for a, b in T1_VALUE:
        v = re.sub(a, b, v)
    v = esc(v)
    for a, b in T1_TEX:
        v = v.replace(a, b)
    return v


# Table 3 (ablation, tables_p2 Table 6) blocks; Table 4 (claims, tables_p2 Table 3) sets, roles and verdicts
ABL_BLOCK = {"circle, dev circle_main": "circle, development", "circle, CONFIRM2": "circle, held-out",
             "hover, dev N6_hover": "hover, development",
             "hover, dev N6_hover, subset A": "hover, development, PA-MOBADC unsat.",
             "hover, CONFIRM2": "hover, held-out"}
CL_SET = {"dev circle_main": "dev., circle", "CONFIRM2 circle": "held-out, circle", "dev N6_hover": "dev., hover",
          "CONFIRM2 hover": "held-out, hover", "dev S40": "dev., circle, 1/day",
          "dev N5-H-StrongRel": "dev., hover, strong wind", "CONFIRM2 H-hover band": "held-out, hover, strong wind"}
CL_ROLE = {"CLAIM-dev": "registered gate", "CLAIM": "registered claim", "POST-HOC": "post hoc"}
CL_VERDICT = {"PASS (sec 0.5)": "passed", "CONFIRMED": "confirmed", "CONFIRMED (n_unsafe 0)": "confirmed",
              "NOT CONFIRMABLE": "not scorable", "-": "--"}


def cl_claim(c):
    return esc(c.replace(" (A)", " (unsat.)").replace(" (full one set)", ", all segments"))


def md_tables(path):
    """{number: [rows]} of the '## Table N' sections of tables_p2.md (header row first)."""
    text = path.read_text(encoding="utf-8")
    out = {}
    for m in re.finditer(r"^## Table (\d+)(.*?)(?=^## Table |\Z)", text, re.M | re.S):
        rows = [ln for ln in m.group(2).splitlines() if ln.startswith("|")]
        rows = [r for r in rows if not re.match(r"^\|[-|\s]+\|$", r)]
        out[int(m.group(1))] = [[c.strip() for c in r.strip().strip("|").split("|")] for r in rows]
    return out


def result_rows(*paths):
    """id -> (value, SE) from the generated RESULTS tables (the reproduction table: final-run value and SE)."""
    out = {}
    for p in paths:
        for ln in p.read_text(encoding="utf-8").splitlines():
            if not ln.startswith("| `"):
                continue
            c = [x.strip() for x in ln.strip().strip("|").split("|")]
            key = c[0].strip("`")
            if key in out or len(c) < 5:
                continue
            if re.match(r"^\S+ / \S+$", c[4]):
                out[key] = (c[3], c[4].split(" / ")[1])
            else:
                out[key] = (c[2], c[3])
    return out


def table_env(head, body, widths, caption, label, sideways=False):
    """A numbered table in the class's own float (sn-jnl wraps it in threeparttable, which cannot sit inside a
    \\resizebox): ragged-right p-columns as fractions of the line width, so long cells wrap instead of being
    scaled; the widest tables are set sideways (\\linewidth is then the text height)."""
    spec = "@{}" + "".join(f">{{\\raggedright\\arraybackslash}}p{{{w}\\linewidth}}" for w in widths) + "@{}"
    env = "sidewaystable" if sideways else "table"
    pos = "" if sideways else "[!htbp]"
    return (f"\\begin{{{env}}}{pos}\n\\caption{{{caption}}}\\label{{{label}}}\n\\setlength{{\\tabcolsep}}{{3pt}}\n"
            f"\\begin{{tabular}}{{{spec}}}\n\\toprule\n"
            + " & ".join(head) + " \\\\\n\\midrule\n" + "\n".join(" & ".join(r) + r" \\" for r in body)
            + f"\n\\botrule\n\\end{{tabular}}\n\\end{{{env}}}\n")


def paper_tables():
    T = md_tables(TAB)
    R = result_rows(RESF, RESP)
    t = {}
    # Table 1 - parameters (tables_p2 Table 1)
    rows = [[lookup(T1_LABEL, r[0], "Table 1 quantity"), t1_value(r[1]), t1_source(r[2])] for r in T[1][1:]]
    t[1] = table_env(["quantity", "value", "source"], rows, [0.33, 0.39, 0.20],
                     "Parameters of plant P2 and of the controllers.", TABLABEL[1])
    # Table 2 - main comparison (tables_p2 Table 5)
    head = ["controller", "mean [m] (SE; by-day median)", "median of segment means [m]", "STD [m]",
            "median of segment STDs [m]", "$\\theta$ RMS [\\textdegree]"]
    assert len(T[5][0]) == len(head)
    t[2] = table_env(head, [[esc(x) for x in r] for r in T[5][1:]], [0.19, 0.26, 0.12, 0.10, 0.12, 0.09],
                     "Eight controllers on the development circle (133 segments, 42 days; one segment left out "
                     "because PAW-MOBADC stopped on it). Mean = pooled mean position-error norm with day-jackknife "
                     "SE and by-day median; STD = within-segment standard deviation of the error norm, pooled; "
                     "$\\theta$ RMS = payload cable angle, mostly the steady cone angle on the circle (15.0\\textdegree{} "
                     "without wind). ``+ trim'' = known payload weight added to the force command.", TABLABEL[2])
    # Table 3 - ablation (tables_p2 Table 6)
    head = ["block", "segments (days)", "MOBADC-W [m]", "PA-MOBADC [m]", "PAW-MOBADC [m]",
            "C1: PA-MOBADC / MOBADC-W $-$ 1", "C2: PAW-MOBADC / PA-MOBADC $-$ 1", "total: PAW-MOBADC / MOBADC-W $-$ 1"]
    assert len(T[6][0]) == len(head)
    rows = [[lookup(ABL_BLOCK, r[0], "Table 3 block")] + [esc(x) for x in r[1:]] for r in T[6][1:]]
    t[3] = table_env(head, rows, [0.14, 0.07, 0.075, 0.075, 0.075, 0.155, 0.155, 0.155],
                     "Ablation MOBADC-W $\\rightarrow$ PA-MOBADC (C1) $\\rightarrow$ PAW-MOBADC (C2): pooled error of "
                     "each stage on the block's common set of segments and the step changes (SE; leave-one-out range; "
                     "by-day median). ``unsat.'' = segments on which PA-MOBADC is below its tilt clamp. MOBADC-W was "
                     "not run in hover.", TABLABEL[3], sideways=True)
    # Table 4 - registered claims (tables_p2 Table 3, first nine columns)
    head = ["claim", "set", "role", "value", "SE", "leave-one-out range", "by-day median", "segments (days)",
            "verdict"]
    rows = [[cl_claim(r[0]), lookup(CL_SET, r[1], "Table 4 set"), lookup(CL_ROLE, r[2], "Table 4 role")]
            + [esc(x) for x in r[3:8]] + [lookup(CL_VERDICT, r[8], "Table 4 verdict")] for r in T[3][1:]]
    t[4] = table_env(head, rows, [0.21, 0.13, 0.09, 0.07, 0.05, 0.12, 0.07, 0.07, 0.08],
                     "The claims on the development set and on the held-out days (Section~\\ref{sec:registration-and-"
                     "held-out-confirmation}): value, day-jackknife SE, leave-one-segment-out range, by-day median, "
                     "and the verdict of the registered test. ``unsat.'' = scored on the segments on which PA-MOBADC "
                     "is below its tilt clamp; ``1/day'' = one segment per day.", TABLABEL[4], sideways=True)
    # Table 5 - C1 across payload mass and cable length (tables_p2 Table 4)
    head = ["($m_p$, $L$)", "$\\tau$ [ms]", "segments", "MOBADC [m]", "MOBADC-W [m]", "PA-MOBADC [m]",
            "MOBADC-W + preview [m]", "PA-MOBADC / MOBADC-W $-$ 1", "(MOBADC-W + preview) / MOBADC-W $-$ 1"]
    assert len(T[4][0]) == len(head)
    rows = [[esc(x).replace("U\\_max", "$U_{\\max}$") for x in r] for r in T[4][1:]]
    t[5] = table_env(head, rows, [0.09, 0.05, 0.10, 0.07, 0.07, 0.07, 0.07, 0.18, 0.18],
                     "C1 across payload mass $m_p$ [kg] and cable length $L$ [m] on the development circle, one segment "
                     "per day: horizon, segments used, pooled errors and the changes against MOBADC-W (SE; "
                     "leave-one-out range; by-day median). The light-payload rows are pooled on the segments inside "
                     "their wind envelope $U \\le U_{\\max}$.", TABLABEL[5], sideways=True)
    # Table 6 - what the payload-drag term depends on (RESULTS_FINAL / RESULTS_P2 ids)
    spec = [("circle, nominal $\\hat K$", "circle, 1/day", "E3-c", "E4-circle-fair"),
            ("circle, $\\hat K\\times0.7$", "circle, 1/day", "E3-c070", None),
            ("circle, $\\hat K\\times1.3$", "circle, 1/day", "E3-c130", None),
            ("hover, nominal $\\hat K$", "hover, 1/day", "Hs-S40h", None),
            ("hover, $\\hat K\\times0.7$", "hover, 1/day", "Hs-S40h-k070", None),
            ("hover, $\\hat K\\times1.3$", "hover, 1/day", "Hs-S40h-k130", None),
            ("circle, wind-sensor noise 0.1 m/s", "circle, 1/day", "E1-c", None),
            ("hover, wind-sensor noise 0.1 m/s", "hover, 1/day", "E1-h", None),
            ("circle, spike filter on the measured wind", "circle, unsat.", "E2-c-A", None),
            ("circle, no filter", "circle, unsat.", "E2-c0-A", None),
            ("hover, spike filter on the measured wind", "hover, unsat.", "E2-h-A", None),
            ("hover, no filter", "hover, unsat.", "E2-h0-A", None),
            ("figure-eight", "figure-eight", "E4-T3b-C2", "E4-T3b-fair"),
            ("square", "square", "E4-square-C2", "E4-square-fair"),
            ("circle, $L$ = 0.5 m", "circle, 1/day", "E4-L050-C2", "E4-L050-fair"),
            ("circle, $L$ = 1.5 m", "circle, 1/day", "E4-L150-C2", "E4-L150-fair"),
            ("circle, $m_p$ = 0.25 kg", "circle, 1/day, $U \\le U_{\\max}$", "E4-mp025-C2-env", "E4-mp025-fair-env"),
            ("circle, $m_p$ = 0.65 kg", "circle, 1/day", "E4-mp065-C2", "E4-mp065-fair"),
            ("circle, added to the preview", "circle, 1/day", "E4-circle-C2V", "E4-circle-fairV"),
            ("figure-eight, added to the preview", "figure-eight", "E4-T3b-C2V", "E4-T3b-fairV"),
            ("square, added to the preview", "square", "E4-square-C2V", "E4-square-fairV")]
    rows = []
    for cond, st, a, b in spec:
        for k in (a, b):
            if k and k not in R:
                raise SystemExit(f"build_tex: result id {k} not in RESULTS_FINAL / RESULTS_P2")
        rows.append([cond, st, esc(f"{R[a][0]} ({R[a][1]})"), esc(f"{R[b][0]} ({R[b][1]})") if b else "--"])
    t[6] = table_env(["condition", "development set", "gain $h$ of the payload-drag term (SE)",
                      "complete controller / MOBADC-W $-$ 1 (SE)"], rows, [0.34, 0.20, 0.18, 0.18],
                     "What the payload-drag term depends on (development set, descriptive). $h = 1 -$ PAW-MOBADC / "
                     "PA-MOBADC; in the preview rows the term is added to MOBADC-W + preview and $h = 1 -$ "
                     "(PAW-MOBADC + preview) / (MOBADC-W + preview). ``1/day'' = one segment per day; ``unsat.'' = "
                     "segments on which PA-MOBADC is below its tilt clamp.", TABLABEL[6])
    return t


# ---------------------------------------------------------------- manuscript conversion
def split_sections(md):
    """[(level, title, body)] for '## ' / '### ' headings."""
    parts = re.split(r"^(#{2,3}) (.+)$", md, flags=re.M)
    out = [(0, "", parts[0])]
    for i in range(1, len(parts), 3):
        out.append((len(parts[i]), parts[i + 1].strip(), parts[i + 2]))
    return out


def sec_name(ttl):
    return re.sub(r"^(\d+(\.\d+)?\.?|Appendix [A-Z]\.)\s*", "", ttl)


def sec_label(name):
    return "sec:" + re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")


def inline_table(md_block):
    rows = [ln for ln in md_block.strip().splitlines() if ln.startswith("|")]
    rows = [r for r in rows if not re.match(r"^\|[-|\s]+\|$", r)]
    cells = [[c.strip() for c in r.strip().strip("|").split("|")] for r in rows]
    n = len(cells[0])

    def conv(c):
        x = pandoc(equations(c)).strip()
        return x if x else c

    spec = "p{0.32\\linewidth}p{0.6\\linewidth}" if n == 2 else "p{0.46\\linewidth}" + "p{0.22\\linewidth}" * (n - 1)
    lines = [" & ".join(r"\textbf{" + conv(c) + "}" for c in cells[0]) + r" \\", r"\midrule"]
    lines += [" & ".join(conv(c) for c in r) + r" \\" for r in cells[1:]]
    return ("\n\\begin{center}\\footnotesize\n\\begin{tabular}{@{}" + spec + "@{}}\n\\toprule\n" + "\n".join(lines) +
            "\n\\botrule\n\\end{tabular}\n\\end{center}\n")


def protect_tables(body, store):
    def rep(m):
        store.append(inline_table(m.group(0)))
        return f"\n\nTABLEPLACEHOLDER{len(store) - 1}\n\n"
    return re.sub(r"(?:^\|.*\|\s*$\n?)+", rep, body, flags=re.M)


SPLIT = {"eq:ff-err"}   # wider than the text block of the template (overfull in the LaTeX log): two lines


def eq_body(body, label):
    body = body.strip()
    if label in SPLIT:
        body = "\\begin{gathered}\n" + body.replace(",\\qquad", ",\\\\") + "\n\\end{gathered}"
    return body


def equations(md):
    md = re.sub(r"\$\$(.+?)\$\$\s*\{#(eq:[A-Za-z0-9_-]+)\}",
                lambda m: "\n\\begin{equation}\n" + eq_body(m.group(1), m.group(2)) + "\n\\label{" + m.group(2)
                + "}\n\\end{equation}\n", md, flags=re.S)
    md = re.sub(r"\(@(eq:[A-Za-z0-9_-]+)\)", lambda m: "\\eqref{" + m.group(1) + "}", md)
    md = re.sub(r"@(eq:[A-Za-z0-9_-]+)", lambda m: "Eq.~\\eqref{" + m.group(1) + "}", md)
    return md


def propositions(tex):
    tex = re.sub(r"\\textbf\{(Proposition \d+) \((.+?)\)\.\}\s*", lambda m: "\\begin{proposition}[" + m.group(2) + "]\n",
                 tex)
    # a proposition ends where its proof starts; a proof ends at \square
    tex = re.sub(r"\n\s*\\emph\{Proof\.\}\s*", lambda m: "\n\\end{proposition}\n\\begin{proof}\n", tex)
    tex = re.sub(r"\s*\\\(\\square\\\)", lambda m: "\n\\end{proof}", tex)
    tex = re.sub(r"\s*\$\\square\$", lambda m: "\n\\end{proof}", tex)
    return tex


def cross_refs(tex, secmap):
    num = r"\d+(?:\.\d+)?(?!\.\d)"

    def sec(n):
        if n not in secmap:
            raise SystemExit(f"build_tex: Section {n} cited but no such heading")
        return "\\ref{" + secmap[n] + "}"

    def secs(m):
        word, rest = m.group(1), m.group(2)
        rest = re.sub(r"(\d+(?:\.\d+)?)--(\d+(?:\.\d+)?)", lambda k: sec(k.group(1)) + "--" + sec(k.group(2)), rest)
        rest = re.sub(r"(?<![{\w.-])(\d+(?:\.\d+)?)(?![\w.}-]*\})", lambda k: sec(k.group(1)), rest)
        return word + "~" + rest

    tex = re.sub(r"\b(Sections?) (" + num + r"(?:(?:, | and |--)" + num + r")*)", secs, tex)
    tex = re.sub(r"\bFig\. (\d+)", lambda m: "Fig.~\\ref{fig:" + m.group(1) + "}", tex)
    tex = re.sub(r"\bTable (\d+)", lambda m: "Table~\\ref{" + TABLABEL[int(m.group(1))] + "}", tex)
    tex = re.sub(r"et al\.~(?=[A-Z])", lambda m: "et al.\\@ ", tex)
    return tex


def figures(md):
    caps = {}
    for m in re.finditer(r"\*\*Fig\. (\d+)\*\* \(`([^`]+)`\)\. (.+?)(?=\n\n|\Z)", md, re.S):
        caps[int(m.group(1))] = (m.group(2), " ".join(m.group(3).split()))
    return caps


def fig_env(n, f, cap):
    capt = pandoc(cap).strip()
    return (f"\n\\begin{{figure}}[!htbp]\n\\centering\n\\includegraphics[width=\\linewidth]{{{f}.pdf}}\n"
            f"\\caption{{{capt}}}\\label{{fig:{n}}}\n\\end{{figure}}\n")


PREAMBLE = r"""% GENERATED by paper/ijdc/build_tex.py from paper/manuscript.md - do not edit by hand.
\documentclass[lineno,12pt]{sn-jnl}% IJDC template: Math and Physical Sciences Reference Style
\usepackage{cite}%
\usepackage{graphicx}%
\usepackage{multirow}%
\usepackage{amsmath,amssymb,amsfonts}%
\usepackage{amsthm}%
\usepackage{mathrsfs}%
\usepackage[title]{appendix}%
\usepackage{xcolor}%
\usepackage{textcomp}%
\usepackage{manyfoot}%
\usepackage{booktabs}%
\usepackage{bm}%
\usepackage{array}%
\graphicspath{{../figures/}{figures/}}
\providecommand{\tightlist}{\setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\theoremstyle{thmstyleone}%
\newtheorem{proposition}{Proposition}%
\raggedbottom
\begin{document}
"""


def main():
    md = MAN.read_text(encoding="utf-8")
    md = re.sub(r"^---\n.*?\n---\n", "", md, flags=re.S)
    title = re.search(r"^# (.+)$", md, re.M).group(1).strip()
    abstract = re.search(r"^## Abstract\s*\n(.*?)\n\*\*Keywords:\*\*", md, re.M | re.S).group(1).strip()
    keywords = re.search(r"^\*\*Keywords:\*\*\s*(.+)$", md, re.M).group(1).strip()
    caps = figures(md)
    tables = paper_tables()
    secs = split_sections(md)
    secmap = {}
    for lvl, ttl, _ in secs:
        m = re.match(r"^(\d+(?:\.\d+)?)\.?\s", ttl)
        if m:
            secmap[m.group(1)] = sec_label(sec_name(ttl))
    store, body, appendix, data = [], [], [], ""
    in_app = False
    placed_fig, placed_tab = set(), set()
    for lvl, ttl, txt in secs:
        if lvl == 0 or ttl in ("Abstract", "Figure captions", "References"):
            continue
        if ttl.startswith("Data and code availability"):
            data = pandoc(txt).strip()
            continue
        if ttl.startswith("Appendix A"):
            in_app = True
        name = sec_name(ttl)
        tex = propositions(pandoc(equations(protect_tables(txt, store))))
        # place each figure / table after the paragraph that first cites it
        outp = []
        for p in tex.split("\n\n"):
            outp.append(p)
            for m in re.finditer(r"Fig\.~?\s?(\d+)", p):
                n = int(m.group(1))
                if n not in placed_fig and n in caps:
                    outp.append(fig_env(n, *caps[n]))
                    placed_fig.add(n)
            for m in re.finditer(r"Table~?\s?(\d+)", p):
                n = int(m.group(1))
                if n not in placed_tab and n in tables:
                    outp.append(tables[n])
                    placed_tab.add(n)
        tex = "\n\n".join(outp)
        tex = re.sub(r"TABLEPLACEHOLDER(\d+)", lambda m: store[int(m.group(1))], tex)
        cmd = "\\section" if lvl == 2 else "\\subsection"
        if ttl == "Notation":
            cmd = "\\section*"
        block = f"{cmd}{{{name}}}\\label{{{sec_label(name)}}}\n\n{tex}\n"
        (appendix if in_app else body).append(block)
    missing = [n for n in caps if n not in placed_fig] + [f"T{n}" for n in tables if n not in placed_tab]
    if missing:
        raise SystemExit(f"build_tex: never cited, not placed: {missing}")
    if sorted(placed_fig) != list(range(1, len(caps) + 1)):
        raise SystemExit(f"build_tex: figures not numbered 1..n: {sorted(placed_fig)}")
    out = [PREAMBLE,
           "\\title[" + title.split(" of a ")[0] + "]{" + title + "}\n\n",
           "\\abstract{" + pandoc(abstract).strip() + "}\n\n",
           "\\keywords{" + ", ".join(k.strip() for k in keywords.split(";")) + "}\n\n\\maketitle\n\n"]
    out.extend(body)
    out.append("\\backmatter\n\n\\bmhead{Data availability}\n" + data + "\n\n")
    out.append("\\bmhead{Declarations}\nCompeting interests, funding and the authors' contributions are stated on the "
               "separate title page (double-anonymous review); the use of AI-assisted tools is described in "
               "Section~\\ref{sec:use-of-ai-assisted-tools}.\n\n")
    if appendix:
        out.append("\\begin{appendices}\n\n" + "\n".join(appendix) + "\\end{appendices}\n\n")
    out.append("\\bibliographystyle{sn-nature}\n\\bibliography{references}\n\n\\end{document}\n")
    s = "".join(out)
    s = re.sub(r"\\cite[pt]\{", lambda m: "\\cite{", s)
    s = cross_refs(s.replace("–", "--"), secmap)
    s = unicode_fix(s)
    # a sentence that continues after a display equation is not a new paragraph (no indent)
    s = re.sub(r"(\\end\{equation\}\n)\n+(?=[a-z\\(])", lambda m: m.group(1), s)
    left = re.findall(r"\(@eq:|\[@|TABLEPLACEHOLDER|\\pandocbounded", s)
    if left:
        raise SystemExit(f"build_tex: unconverted markup left: {sorted(set(left))}")
    (OUT / "manuscript.tex").write_text(s, encoding="utf-8", newline="\n")
    shutil.copyfile(ROOT / "paper" / "references.bib", OUT / "references.bib")
    print(f"wrote {OUT / 'manuscript.tex'}; figures {sorted(placed_fig)}, tables {sorted(placed_tab)}, "
          f"{len(re.findall(r'begin.equation', s))} equations")


if __name__ == "__main__":
    main()
