#!/usr/bin/env python3
"""
readme_names.py -- the README table "name in the paper <-> code in the result files <-> result files", generated.

    python3 tools/readme_names.py            # print the table
    python3 tools/readme_names.py --write    # replace the block between the markers in README.md
    python3 tools/readme_names.py --check    # exit 1 if README.md's block differs (run by CI)

Names come from analysis/p2_names.m (the single map). Files come from the (file, columns) pairs the generators read:
analysis/make_results_p2.m (its specs) and analysis/make_p2_tables.m. Nothing is typed by hand.
"""

import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
BEGIN = "<!-- names-table: generated by tools/readme_names.py; do not edit -->"
END = "<!-- /names-table -->"


def names():
    t = (ROOT / "analysis" / "p2_names.m").read_text(encoding="utf-8")
    m = re.search(r"M = \{(.*?)\};", t, flags=re.S)
    pairs = re.findall(r"'([^']+)',\s*'([^']+)'", m.group(1))
    return pairs


def files_by_code():
    out = {}
    D2 = {"D2d": "gd6/d2_p2.mat", "D2c": "gd10/D2.mat"}
    for src in ("make_results_p2.m", "make_p2_tables.m"):
        t = (ROOT / "analysis" / src).read_text(encoding="utf-8")
        for m in re.finditer(r"(\{[^{}]*\}|'gd\d+/[^']+\.mat'|D2[dc]),\s*(\{[^{}]*\})", t):
            fs = re.findall(r"'(gd\d+/[^']+\.mat)'|\b(D2[dc])\b", m.group(1))
            fs = [a or D2[v] for a, v in fs]
            cs = re.findall(r"'([A-Za-z0-9_+]+)'", m.group(2))
            if len(fs) == len(cs) and len(fs) > 1:
                pairs = zip(cs, fs)
            else:
                pairs = [(c, f) for c in cs for f in fs]
            for c, f in pairs:
                if f:
                    out.setdefault(c, set()).add(f)
        # table sources written as {'Code', 'gd6/file.mat'; ...} (make_p2_tables only: elsewhere the first string
        # of such a pair is a display name)
        if src == "make_p2_tables.m":
            for c, f in re.findall(r"'([A-Za-z0-9_+]+)',\s*'(gd\d+/[^']+\.mat)'", t):
                out.setdefault(c, set()).add(f)
    for c, f in (("O", "gd7/N5-*.mat, gd7/N4b-*.mat"), ("O_6", "gd7/N6.mat"), ("L3_6", "gd7/N6.mat")):
        out.setdefault(c, set()).add(f)
    return out


def table():
    fb = files_by_code()
    rows = ["| name in the paper | code in the result files | result files with this column |", "|---|---|---|"]
    for code, name in names():
        if not fb.get(code):
            continue                                   # a code no generator of the paper reads
        fs = ", ".join(f"`{x}`" for x in sorted(fb[code]))
        rows.append(f"| {name} | `{code}` | {fs} |")
    return "\n".join([BEGIN, ""] + rows + ["", END])


def main():
    blk = table()
    readme = ROOT / "README.md"
    if "--write" in sys.argv or "--check" in sys.argv:
        t = readme.read_text(encoding="utf-8")
        m = re.search(re.escape(BEGIN) + r".*?" + re.escape(END), t, flags=re.S)
        if not m:
            print("README.md has no names-table markers")
            sys.exit(1)
        if "--check" in sys.argv:
            ok = m.group(0) == blk
            print("  README names table " + ("PASS" if ok else "FAIL: out of date - run tools/readme_names.py --write"))
            sys.exit(0 if ok else 1)
        readme.write_text(t[:m.start()] + blk + t[m.end():], encoding="utf-8")
        print("README.md names table written")
        return
    print(blk)


if __name__ == "__main__":
    main()
