function make_p2_tables(varargin)
%MAKE_P2_TABLES  GD11 tables 1-6 (REGISTER_P2 sec 62.2, 63.2-63.3) -> paper/tables/tables_p2.md, from saved results only.
%
%   make_p2_tables
%   make_p2_tables('Out', 'tables.md', 'Root', 'results')
%
%  1 parameters (read from core/p2_params.m and init_MOBADC_params at run time, labelled [PAPER] / [THIS WORK] /
%    [DERIVED]); 2 Guo's controllers on circle_main (+ trim); 3 the claims, dev and CONFIRM2, with u_osc and theta RMS
%    of the compared columns; 4 sensitivity on S40 circle at every m_p / L level and 2^2 corner (m_p 0.25 rows on
%    U <= 7.38 m/s, sec 50.1) + a trend sentence generated from the numbers; 5 main comparison on dev circle_main
%    (sec 63.2: PID / DO (+ trim), ESO, MOBADC, INDI-DE, PAW-MOBADC; mean, Guo STD, theta RMS); 6 ablation
%    MOBADC-W -> PA-MOBADC -> PAW-MOBADC (sec 63.3). Names: analysis/p2_names.m. Statistics: analysis/p2r_stat.m.
opt = struct('Out', fullfile(repo_root(), 'paper', 'tables', 'tables_p2.md'), 'Root', fullfile(repo_root(), 'results'));
for i = 1:2:numel(varargin)
    assert(isfield(opt, varargin{i}), 'make_p2_tables: unknown option ''%s''.', varargin{i});
    opt.(varargin{i}) = varargin{i+1};
end
[st, gh] = system('git rev-parse --short HEAD');  if st ~= 0, gh = 'unknown'; end
L = {};
L{end + 1} = '# TABLES_P2 - tables 1-6 of the paper (generated)';
L{end + 1} = '';
L{end + 1} = sprintf(['> Generated by `analysis/make_p2_tables.m` at git `%s` on %s (REGISTER_P2 sec 62.2). Do not ' ...
    'edit by hand. Statistics: pooled = sqrt(mean(m_i^2)); SE = paired day jackknife; LOO [min, max]; by-day median.'], ...
    strtrim(gh), datestr(now, 'yyyy-mm-dd HH:MM'));
L = [L, table1(), table2(opt.Root), table3(opt.Root), table4(opt.Root), table5(opt.Root), table6(opt.Root)];
fid = fopen(opt.Out, 'w');
assert(fid > 0, 'make_p2_tables: cannot write %s.', opt.Out);
fprintf(fid, '%s\n', L{:});
fclose(fid);
fprintf('  wrote %s\n', opt.Out);
end

%% ---------------------------------------------------------------------
function L = table1()
P = p2_params();
evalc('evalin(''base'', ''init_MOBADC_params'')');
g = @(n) evalin('base', n);
dg = @(M) ['diag(' strjoin(arrayfun(@(v) sprintf('%g', v), diag(M).', 'UniformOutput', false), ', ') ')'];
R = {
    'quadrotor mass m_Q', sprintf('%g kg', P.m_Q), '[PAPER] Guo 2020 A.1'
    'payload mass m_p', sprintf('%g kg (sensitivity 0.25, 0.65)', P.m_L), '[THIS WORK]'
    'cable length L', sprintf('%g m (sensitivity 0.5, 1.5)', P.L), '[THIS WORK]'
    'payload damping zeta_s', sprintf('%g', P.zeta_s), '[THIS WORK]'
    'payload drag ratio K = (C_D A)_L / (C_D A)_Q', sprintf('%g', P.K), '[THIS WORK]'
    'wind-force gain K_w', sprintf('%g N/(m/s) at U_ref %g m/s', P.K_w, P.U_ref), '[DERIVED]'
    'motor lag tau_m', sprintf('%g ms (D1; stress 25, 30 ms)', 1000 * P.tau_m), '[THIS WORK]'
    'rotor force limit f_max', sprintf('%.4g N', P.f_max), '[THIS WORK] (Quanser v0.4 model)'
    'total thrust limit F_TOT_MAX', sprintf('%.5g N', P.F_TOT_MAX), '[THIS WORK]'
    'torque limit TAU_MAX', '0.5 N m per axis', '[THIS WORK] assumption (MOBADC_FIDELITY E13)'
    'tilt clamp', '30 deg', '[THIS WORK]'
    'position loop / mocap', sprintf('%g Hz, delay %g ms, sigma %g mm', P.fs_pos, 1000 * P.delay_pos, 1000 * P.sig_pos), '[THIS WORK]'
    'attitude loop / IMU', sprintf('%g Hz; noise density acc %.3g (m/s^2)/sqrt(Hz), gyro %.3g (rad/s)/sqrt(Hz)', P.fs_att, P.N_acc, P.N_gyro), '[THIS WORK] (BMI160)'
    'wind sensor', sprintf('%g Hz, delay %g ms, sigma 0 in every run (D3)', P.fs_wind, 1000 * P.delay_wind), '[THIS WORK]'
    'K_gamma (position)', dg(g('Kgamma')), '[PAPER] Guo 2020 A.2'
    'K_nu (velocity)', dg(g('Kv')), '[PAPER] Guo 2020 A.2'
    'K_eta / K_omega (attitude)', [dg(g('K_eta')) ' / ' dg(g('K_omega'))], '[PAPER] Guo 2020 A.2'
    'attitude ESO Ka1 / Ka2 / Ka3', sprintf('%g / %g / %g (x I3)', g('Ka1(1)'), g('Ka2(1)'), g('Ka3(1)')), '[PAPER] Guo 2020 A.2'
    'payload prediction horizon tau*', '290 ms circle, 0 hover (N0P, sec 7.1)', '[THIS WORK] measured on dev'
    'reference preview tau_prev*', '180 ms (sec 7.1)', '[THIS WORK] measured on dev'
    'PAW-MOBADC payload-wind feed-forward factor 1 + K-hat', '1.5 (K-hat = K = 0.5)', '[THIS WORK] (D20)'
    'INDI-type filter cut-off omega_f', '32 Hz (D21)', '[THIS WORK]'
    };
L = {'', '## Table 1 - parameters', '', '| quantity | value | source |', '|---|---|---|'};
for k = 1:size(R, 1), L{end + 1} = sprintf('| %s | %s | %s |', R{k, :}); end %#ok<AGROW>
end

%% ---------------------------------------------------------------------
function L = table2(root)
L = {'', '## Table 2 - Guo''s controllers on circle_main (dev)', ''};
[Z, cols, ok] = p2r_load(root, 'gd6/guo_p2.mat');
if ~ok, L{end + 1} = '`gd6/guo_p2.mat` not found.'; return; end
[E, day, ~, keep] = p2r_subset(Z, cols, cols, 'one4');
E = E(keep, :);  day = day(keep);
P = sqrt(mean(E.^2, 1));
L{end + 1} = sprintf('One set %d of %d segments, %d days. Role: DESCRIPTIVE (reproduction of Guo et al. 2020).', ...
    size(E, 1), numel(keep), numel(unique(day)));
L{end + 1} = '';
L{end + 1} = '| controller | pooled [m] | vs PID (SE; LOO; by-day) |';
L{end + 1} = '|---|---|---|';
for c = 1:numel(cols)
    if c == 1, s = '-'; else, s = fmt(p2r_stat(@(p) p(2) / p(1) - 1, E(:, [1 c]), day)); end
    L{end + 1} = sprintf('| %s | %.5f | %s |', p2_names(cols{c}), P(c), s); %#ok<AGROW>
end
[Zt, ct, okt] = p2r_load(root, 'gd6/guo_trim_p2.mat');
if ~okt, L{end + 1} = ''; L{end + 1} = '`gd6/guo_trim_p2.mat` not found.'; return; end
for c = 1:numel(ct)
    base = strrep(ct{c}, '+trim', '');
    [Ej, dj] = joinrows(Z, cols, {base, 'MOBADC'}, Zt, ct, ct(c));
    s1 = fmt(p2r_stat(@(p) p(3) / p(1) - 1, Ej, dj));
    s2 = fmt(p2r_stat(@(p) p(3) / p(2) - 1, Ej, dj));
    L{end + 1} = sprintf('| %s | %.5f | vs %s: %s; vs MOBADC: %s (n %d) |', p2_names(ct{c}), sqrt(mean(Ej(:, 3).^2)), p2_names(base), ...
        s1, s2, size(Ej, 1)); %#ok<AGROW>
end
end

%% ---------------------------------------------------------------------
function L = table3(root)
L = {'', '## Table 3 - the claims (REGISTER_P2 sec 60.3), dev and CONFIRM2', '', ...
    ['Columns u_osc (RMS oscillation of the commanded rotor forces, §60.4) and theta RMS (payload swing, deg) are ' ...
     'pooled over the scored subset for the two compared columns; dev rows store theta but not u_osc ("-").'], '', ...
    '| claim | set | role | value | SE | LOO | by-day | n (days) | verdict | u_osc [N] (a / b) | theta RMS [deg] (a / b) |', ...
    '|---|---|---|---|---|---|---|---|---|---|---|'};
hh = @(p) 1 - p(2) / p(1);  rel = @(p) p(1) / p(2) - 1;
C = {   % claim, file, cols {a b}, fun, subset, set, role, test
    'D2: PA-MOBADC / MOBADC-W - 1', 'gd6/d2_p2.mat', {'L3', 'L2'}, rel, 'one4', 'dev circle_main', 'CLAIM-dev', 'd2dev'
    'D2: PA-MOBADC / MOBADC-W - 1', 'gd10/D2.mat', {'L3', 'L2'}, rel, 'one4', 'CONFIRM2 circle', 'CLAIM', 'd2'
    'H-static: 1 - PAW-MOBADC / PA-MOBADC (A)', 'gd7/static-hover.mat', {'L3', 'L3_iii0'}, hh, 'unsatL3', 'dev N6_hover', 'POST-HOC', ''
    'H-static (full one set)', 'gd7/static-hover.mat', {'L3', 'L3_iii0'}, hh, 'one4', 'dev N6_hover', 'POST-HOC', ''
    'H-static: 1 - PAW-MOBADC / PA-MOBADC (A)', 'gd10/C2-hover.mat', {'L3', 'L3_iii0'}, hh, 'unsatL3', 'CONFIRM2 hover', 'CLAIM', 'hs'
    'H-static-circle: 1 - PAW-MOBADC / PA-MOBADC', 'gd7/static-circle.mat', {'L3', 'L3_iii0'}, hh, 'one4', 'dev S40', 'POST-HOC', ''
    'H-static-circle (A)', 'gd10/C2-circle.mat', {'L3', 'L3_iii0'}, hh, 'unsatL3', 'CONFIRM2 circle', 'CLAIM', 'hs'
    'H-hover: 1 - oracle / PA-MOBADC (unsat.)', 'gd7/N5-H-StrongRel.mat', {'L3', 'O'}, hh, 'unsat4', 'dev N5-H-StrongRel', 'POST-HOC', ''
    'H-hover: 1 - oracle / PA-MOBADC (unsat.)', 'gd10/C2-hhover.mat', {'L3', 'O'}, hh, 'unsat4', 'CONFIRM2 H-hover band', 'CLAIM', 'hh'};
for k = 1:size(C, 1)
    [Z, cols, ok] = p2r_load(root, C{k, 2});
    if ~ok
        L{end + 1} = sprintf('| %s | %s | %s | `%s` not found | | | | | | | |', C{k, 1}, C{k, 6}, C{k, 7}, C{k, 2}); %#ok<AGROW>
        continue
    end
    [E, day, ~, keep] = p2r_subset(Z, cols, C{k, 3}, C{k, 5});
    if ~any(keep), L{end + 1} = sprintf('| %s | %s | %s | empty | | | | | | | |', C{k, 1}, C{k, 6}, C{k, 7}); continue; end %#ok<AGROW>
    r = p2r_stat(C{k, 4}, E(keep, :), day(keep));
    v = verdict(C{k, 8}, r, Z, cols, C{k, 3});
    [u, th] = effort(Z, cols, C{k, 3}, keep);
    L{end + 1} = sprintf('| %s | %s | %s | %+.2f %% | %.2f | [%+.2f, %+.2f] | %+.2f %% | %d (%d) | %s | %s | %s |', ...
        C{k, 1}, C{k, 6}, C{k, 7}, 100 * r.val, 100 * r.se, 100 * r.loo, 100 * r.med, r.n, r.nd, v, u, th); %#ok<AGROW>
end
end

function v = verdict(test, r, Z, cols, ab)
suff = r.n >= 15 && r.nd >= 6;
switch test
    case 'd2dev', v = tern(r.val <= -0.30 && r.loo(2) < 0, 'PASS (sec 0.5)', 'FAIL (sec 0.5)');
    case 'd2'
        if ~suff, v = 'NOT CONFIRMABLE'; else, v = tern(r.val <= -0.15 && r.val + 1.65 * r.se < 0, 'CONFIRMED', 'NOT CONFIRMED'); end
    case 'hs'
        E = p2r_E(Z, cols, ab);
        nu = sum(isfinite(E(:, 1)) & ~isfinite(E(:, 2)));
        if ~suff, v = 'NOT CONFIRMABLE';
        else, v = tern(r.med >= 0.10 && r.val - 1.65 * r.se > 0 && nu <= 1, 'CONFIRMED', 'NOT CONFIRMED'); end
        v = sprintf('%s (n_unsafe %d)', v, nu);
    case 'hh'
        if ~suff, v = 'NOT CONFIRMABLE'; else, v = tern(r.med >= 0.10 && r.val - 1.65 * r.se > 0, 'CONFIRMED', 'NOT CONFIRMED'); end
    otherwise, v = '-';
end
end

function [u, th] = effort(Z, cols, ab, keep)
%EFFORT  pooled u_osc (rows.Q(5,:), CONFIRM2 only) and pooled theta RMS (p2 theta_rms_stat_deg) of columns a, b.
u = '-';
if isfield(Z.rows, 'Q')
    q = nan(numel(Z.rows), 2);
    for c = 1:2
        j = find(strcmp(cols, ab{c}), 1);
        for i = 1:numel(Z.rows), q(i, c) = Z.rows(i).Q(5, j); end
    end
    q = q(keep, :);
    u = sprintf('%.3f / %.3f', sqrt(mean(q.^2, 1)));
end
t = p2r_p2(Z, cols, ab, 'theta_rms_stat_deg');
t = t(keep, :);
th = '-';
if all(isfinite(t(:))), th = sprintf('%.2f / %.2f', sqrt(mean(t.^2, 1))); end
end

%% ---------------------------------------------------------------------
function L = table4(root)
L = {'', '## Table 4 - sensitivity, circle on S40 (dev), every level', '', ...
    ['Role: DESCRIPTIVE. Main results stay at L 1.0 m, m_p 0.5 kg. m_p 0.25 rows on the A2 envelope U <= 7.38 m/s ' ...
     '(sec 50.1); segments above it are left out and counted.'], '', ...
    ['| (m_p, L) | tau [ms] | one set | MOBADC | MOBADC-W | PA-MOBADC | MOBADC-W + preview | PA-MOBADC / MOBADC-W - 1 ' ...
     '(SE; LOO; by-day) | (MOBADC-W + preview) / MOBADC-W - 1 (SE; LOO; by-day) |'], ...
    '|---|---|---|---|---|---|---|---|---|'};
T = {   % label, file, U_max
    '(0.5, 1.0) nominal', 'FROMD2', Inf
    '(0.25, 1.0)', 'gd6/tab_circle_mp025_p2.mat', 7.38
    '(0.65, 1.0)', 'gd6/tab_circle_mp065_p2.mat', Inf
    '(0.5, 0.5)', 'gd6/tab_circle_L050_p2.mat', Inf
    '(0.5, 1.5)', 'gd6/tab_circle_L150_p2.mat', Inf
    '(0.25, 0.5)', 'gd6/tab_circle_mp025_L050_p2.mat', 7.38
    '(0.25, 1.5)', 'gd6/tab_circle_mp025_L150_p2.mat', 7.38
    '(0.65, 0.5)', 'gd6/tab_circle_mp065_L050_p2.mat', Inf
    '(0.65, 1.5)', 'gd6/tab_circle_mp065_L150_p2.mat', Inf};
rel = @(p) p(1) / p(2) - 1;
WANT = {'(0.5, 1.0) nominal', -56.22, -61.21;  '(0.25, 1.0)', -39.09, -50.58;   % L3/L2 - 1, V/L2 - 1 [%]
        '(0.25, 0.5)', -42.80, -49.49;  '(0.25, 1.5)', -34.93, -52.62};
V3 = nan(size(T, 1), 1);  VV = V3;
for k = 1:size(T, 1)
    if strcmp(T{k, 2}, 'FROMD2'), [Z, ok] = nominal_s40(root); else, [Z, ~, ok] = p2r_load(root, T{k, 2}); end
    if ~ok, L{end + 1} = sprintf('| %s | | `%s` not found | | | | | | |', T{k, 1}, T{k, 2}); continue; end %#ok<AGROW>
    [E, day, fl, keep] = p2r_subset(Z, {'L0', 'L2', 'L3', 'V'}, {'L0', 'L2', 'L3', 'V'}, 'one4');
    nout = 0;
    if isfinite(T{k, 3})
        U = cellfun(@segU, fl);
        nout = sum(U > T{k, 3});
        keep = keep & ~(U > T{k, 3});
    end
    E = E(keep, :);  day = day(keep);
    P = sqrt(mean(E.^2, 1));
    r3 = p2r_stat(@(p) rel(p([3 2])), E, day);  rv = p2r_stat(@(p) rel(p([4 2])), E, day);
    V3(k) = r3.val;  VV(k) = rv.val;
    w = find(strcmp(WANT(:, 1), T{k, 1}), 1);           % self-check against REGISTER_P2 sec 39.3 / 50.1
    if ~isempty(w)
        g = round(10000 * [r3.val rv.val]) / 100;
        okk = all(abs(g - [WANT{w, 2:3}]) < 0.006);
        fprintf('    table 4 %-20s register %+.2f / %+.2f  recomputed %+.2f / %+.2f  %s\n', T{k, 1}, WANT{w, 2:3}, g, ...
            tern(okk, 'MATCH', 'DIFF'));
    end
    tau = NaN;  if isfield(Z.key, 'TauPred'), tau = 1000 * Z.key.TauPred; end
    L{end + 1} = sprintf('| %s | %.0f | %d/%d%s | %.5f | %.5f | %.5f | %.5f | %s | %s |', T{k, 1}, tau, ...
        size(E, 1), numel(Z.rows), tern(nout > 0, sprintf(' (%d above U_max)', nout), ''), P, fmt(r3), fmt(rv)); %#ok<AGROW>
end
ok = isfinite(V3);
if any(ok)
    [~, i1] = max(V3);  [~, i2] = min(V3);
    L{end + 1} = '';
    L{end + 1} = sprintf(['**Trend (generated from the numbers above):** over the %d levels, PA-MOBADC / MOBADC-W - 1 ' ...
        'lies between %+.1f %% and %+.1f %% (smallest gain at %s, largest at %s); (MOBADC-W + preview) / MOBADC-W - 1 ' ...
        'lies between %+.1f %% and %+.1f %%.'], ...
        sum(ok), 100 * min(V3), 100 * max(V3), T{i1, 1}, T{i2, 1}, 100 * min(VV(ok)), 100 * max(VV(ok)));
end
end

%% ---------------------------------------------------------------------
function L = table5(root)
%TABLE5  REGISTER_P2 sec 63.2: main comparison on dev circle_main in the style of Guo 2020 Table 1 - PID (+ trim),
%  DO (+ trim), ESO, MOBADC (guo_p2 / guo_trim_p2), INDI-DE and PAW-MOBADC (six-circle-h3). One set = finite in
%  the six main rows; trims on the same segments. Columns: pooled mean (SE; by-day median), pooled Guo STD
%  sqrt(mean s_i^2) (Table 1 p. 9), theta RMS. No u_osc, no PA-MOBADC (sec 63.2).
L = {'', '## Table 5 - main comparison on circle_main (dev): circle Test 4, L 1.0 m, m_p 0.5 kg, K 0.5', ''};
src = {'Classical', 'gd6/guo_p2.mat';  'Classical+trim', 'gd6/guo_trim_p2.mat';  'DO', 'gd6/guo_p2.mat';
       'DO+trim', 'gd6/guo_trim_p2.mat';  'ESO', 'gd6/guo_p2.mat';  'MOBADC', 'gd6/guo_p2.mat';
       'H3', 'gd7/six-circle-h3.mat';  'L3_iii0', 'gd7/six-circle-h3.mat'};
main = cellfun(@isempty, strfind(src(:, 1), 'trim'));
C = loadcols(root, src);
if ~all([C(main).ok])
    L{end + 1} = sprintf('Missing: %s (run sec 63.4 first).', strjoin(unique(src(main & ~[C.ok]', 2))', ', '));
    return
end
[fl, day] = oneset(C(main));
L{end + 1} = sprintf(['One set %d segments, %d days (finite in every row except the trims, which use the same ' ...
    'segments). Role: DESCRIPTIVE. PAW-MOBADC (proposed) is post hoc on dev (D20); its confirmation is Table 3. ' ...
    'STD = Guo''s within-segment standard deviation of the position-error norm (Guo 2020 Table 1, p. 9), pooled as ' ...
    'sqrt(mean s_i^2); mean = sqrt(mean m_i^2), SE = paired day jackknife.'], numel(fl), numel(unique(day)));
L = [L, excluded(C(main), src(main, 1))];
L = [L, limits_note(C(main), src(main, 1), fl)];
L{end + 1} = '';
L{end + 1} = ['| controller | mean [m] (SE; by-day median) | median of segment means [m] | STD [m] | median of ' ...
    'segment STDs [m] | theta RMS [deg] |'];
L{end + 1} = '|---|---|---|---|---|---|';
for k = 1:size(src, 1)
    nm = p2_names(src{k, 1});
    if strcmp(src{k, 1}, 'L3_iii0'), nm = [nm ' (proposed)']; end
    if ~C(k).ok, L{end + 1} = sprintf('| %s | `%s` not found | | | | |', nm, src{k, 2}); continue; end %#ok<AGROW>
    [tf, loc] = ismember(fl, C(k).file);
    if ~all(tf), L{end + 1} = sprintf('| %s | %d segment(s) of the set missing | | | | |', nm, sum(~tf)); continue; end %#ok<AGROW>
    E = C(k).E(loc);  m = isfinite(E);
    r = p2r_stat(@(p) p(1), E(m), day(m));
    sd = C(k).SD(loc);  th = C(k).TH(loc);
    md = '-';  if all(isfinite(sd(m))), md = sprintf('%.5f', median(sd(m))); end
    L{end + 1} = sprintf('| %s | %.5f (%.5f; %.5f)%s | %.5f | %s | %s | %s |', nm, r.val, r.se, r.med, ...
        tern(all(m), '', sprintf(' [n %d]', sum(m))), median(E(m)), qm(sd(m), '%.5f'), md, qm(th(m), '%.2f')); %#ok<AGROW>
end
end

function L = limits_note(C, codes, fl)
%LIMITS_NOTE  Segments of the one set at the tilt clamp (tilt_sat_frac >= 1 %) in a row - they dominate the pooled STD
%  (one bad segment's within-segment STD enters squared) - and the theta note: no theta standard deviation is
%  stored, so theta RMS is reported with the steady cone angle of the circle (conical pendulum, no wind).
L = {};
hit = {};  per = cell(1, numel(C));
for k = 1:numel(C)
    [~, loc] = ismember(fl, C(k).file);
    t = C(k).TS(loc);
    per{k} = sprintf('%s %d', p2_names(codes{k}), sum(t >= 0.01));
    hit = union(hit, fl(t >= 0.01));
end
g = 9.81;  R = 0.8;  w = 1.575;  Lc = 1.0;  th = 0.2;      % circle Test 4 (MOBADC_FIDELITY E17 / op_set), L 1.0 m
for it = 1:200, th = atan(w^2 * (R + Lc * sin(th)) / g); end
L{end + 1} = sprintf(['- The pooled STD (sqrt(mean s_i^2)) is dominated by the segments at the actuator limit: %d ' ...
    'segment(s) of the set have the tilt clamp active >= 1 %% of the time in at least one row (per row: %s): %s. The ' ...
    'medians over segments are given beside the pooled values.'], numel(hit), strjoin(per, ', '), ...
    strjoin(cellfun(@(f) ['`' f '`'], hit(:)', 'UniformOutput', false), ', '));
L{end + 1} = sprintf(['- theta RMS is mostly the steady cone angle of the payload on the circle, not swing: a conical ' ...
    'pendulum on this circle without wind has tan(theta_c) = omega^2 (R + L sin(theta_c)) / g, theta_c = %.1f deg ' ...
    '(R %.1f m, omega %.3f rad/s, L %.1f m). The result files store no standard deviation of theta, so the oscillation ' ...
    'about that angle is not reported.'], rad2deg(th), R, w, Lc);
end

%% ---------------------------------------------------------------------
function L = table6(root)
%TABLE6  REGISTER_P2 sec 63.3: ablation MOBADC-W -> PA-MOBADC (C1, prediction) -> PAW-MOBADC (C2, payload-wind
%  compensation), existing numbers only; each block on its own one set (finite in its columns).
L = {'', '## Table 6 - ablation: MOBADC-W -> PA-MOBADC (+ prediction, C1) -> PAW-MOBADC (+ payload-wind compensation, C2)', '', ...
    ['Role: DESCRIPTIVE. Pooled mean error [m] of each stage on the block''s one set; step changes with SE (paired day ' ...
     'jackknife), LOO [min, max] and by-day median. The registered claim values (D2; H-static on the PA-MOBADC-' ...
     'unsaturated subset) are in Table 3. MOBADC-W was not run on hover ("-").'], '', ...
    ['| block | n (days) | MOBADC-W | PA-MOBADC | PAW-MOBADC | C1: PA-MOBADC / MOBADC-W - 1 | C2: PAW-MOBADC / ' ...
     'PA-MOBADC - 1 | total: PAW-MOBADC / MOBADC-W - 1 |'], '|---|---|---|---|---|---|---|---|'};
B = {'circle, dev circle_main', {'L2', 'gd6/d2_p2.mat'; 'L3', 'gd6/d2_p2.mat'; 'L3_iii0', 'gd7/six-circle-h3.mat'};
     'circle, CONFIRM2', {'L2', 'gd10/D2.mat'; 'L3', 'gd10/D2.mat'; 'L3_iii0', 'gd10/C2-circle.mat'};
     'hover, dev N6_hover', {'L3', 'gd7/static-hover.mat'; 'L3_iii0', 'gd7/static-hover.mat'};
     'hover, dev N6_hover, subset A', {'L3', 'gd7/static-hover.mat'; 'L3_iii0', 'gd7/static-hover.mat'};
     'hover, CONFIRM2', {'L3', 'gd10/C2-hover.mat'; 'L3_iii0', 'gd10/C2-hover.mat'}};
rel = @(p) p(1) / p(2) - 1;
notes = {};
for b = 1:size(B, 1)
    src = B{b, 2};
    C = loadcols(root, src);
    if ~all([C.ok])
        L{end + 1} = sprintf('| %s | missing: %s | | | | | | |', B{b, 1}, strjoin(unique(src(~[C.ok], 2))', ', ')); %#ok<AGROW>
        continue
    end
    [fl, day] = oneset(C);
    if ~isempty(strfind(B{b, 1}, 'subset A'))          % sec 60.3 subset A: PA-MOBADC tilt clamp < 1 %
        [~, loc] = ismember(fl, C(1).file);
        keepA = C(1).TS(loc) < 0.01;
        fl = fl(keepA);  day = day(keepA);
    end
    ex = excluded(C, src(:, 1));
    if ~isempty(strfind(B{b, 1}, 'subset A')), ex = {}; end
    if ~isempty(ex), notes{end + 1} = sprintf('%s: %s', B{b, 1}, ex{2}(3:end)); end %#ok<AGROW>
    E = nan(numel(fl), size(src, 1));
    for k = 1:size(src, 1)
        [~, loc] = ismember(fl, C(k).file);  E(:, k) = C(k).E(loc);
    end
    P = sqrt(mean(E.^2, 1));
    w = strcmp(src(:, 1), 'L2');  a = find(strcmp(src(:, 1), 'L3'));  c = find(strcmp(src(:, 1), 'L3_iii0'));
    c2 = fmt(p2r_stat(rel, E(:, [c a]), day));
    if any(w)
        iw = find(w);
        c1 = fmt(p2r_stat(rel, E(:, [a iw]), day));  tot = fmt(p2r_stat(rel, E(:, [c iw]), day));  pw = sprintf('%.5f', P(iw));
    else
        c1 = '-';  tot = '-';  pw = '-';
    end
    L{end + 1} = sprintf('| %s | %d (%d) | %s | %.5f | %.5f | %s | %s | %s |', B{b, 1}, numel(fl), numel(unique(day)), ...
        pw, P(a), P(c), c1, c2, tot); %#ok<AGROW>
    if strcmp(B{b, 1}, 'hover, dev N6_hover')               % what drives the full-set value: the most influential segment
        loo = nan(numel(fl), 1);
        for i = 1:numel(fl), q = E([1:i-1, i+1:end], :);  P2 = sqrt(mean(q.^2, 1));  loo(i) = P2(c) / P2(a) - 1; end
        [~, iw] = max(abs(loo - (P(c) / P(a) - 1)));
        hov = sprintf(['hover, dev N6_hover: on the full set (%d) the most influential segment is `%s` (PA-MOBADC ' ...
            '%.4f m, PAW-MOBADC %.4f m); without it the C2 step moves from %+.2f %% to %+.2f %%. The next row is subset ' ...
            'A (PA-MOBADC tilt clamp < 1 %%, the CONFIRM2 scoring subset of sec 60.3). On CONFIRM2 hover the C2 step is ' ...
            '%s on subset A and %s on the full set.'], ...
            numel(fl), fl{iw}, E(iw, a), E(iw, c), 100 * (P(c) / P(a) - 1), 100 * loo(iw), c2sub(root, 'unsatL3'), ...
            c2sub(root, 'one'));
        notes{end + 1} = hov; %#ok<AGROW>
    end
end
for k = 1:numel(notes), L = [L, {'', ['- ' notes{k}]}]; end %#ok<AGROW>
end

function s = c2sub(root, sub)
%C2SUB  CONFIRM2 hover C2 step PAW-MOBADC / PA-MOBADC - 1 on a subset (for the table 6 note).
s = 'n/a';
[Z, cols, ok] = p2r_load(root, 'gd10/C2-hover.mat');
if ~ok, return; end
[E, day, ~, keep] = p2r_subset(Z, cols, {'L3_iii0', 'L3'}, sub);
if sum(keep) < 2, return; end
r = p2r_stat(@(p) p(1) / p(2) - 1, E(keep, :), day(keep));
s = sprintf('%+.2f %%', 100 * r.val);
end

function L = excluded(C, codes)
%EXCLUDED  The segments the one-set rule leaves out, and which columns are not finite there (stated, never silent).
L = {};
al = {};
for k = 1:numel(C), al = union(al, C(k).file); end
[fl, ~] = oneset(C);
out = setdiff(al, fl);
if isempty(out), return; end
s = cell(1, numel(out));
for i = 1:numel(out)
    bad = {};
    for k = 1:numel(C)
        j = find(strcmp(C(k).file, out{i}), 1);
        if isempty(j), bad{end + 1} = [p2_names(codes{k}) ' (no row)']; %#ok<AGROW>
        elseif ~isfinite(C(k).E(j)), bad{end + 1} = [p2_names(codes{k}) ' not finite']; end %#ok<AGROW>
    end
    s{i} = sprintf('`%s`: %s', out{i}, strjoin(bad, ', '));
end
L = {'', sprintf('- %d segment(s) left out by the one-set rule: %s.', numel(out), strjoin(s, '; '))};
end

function C = loadcols(root, src)
%LOADCOLS  One column per row of src {code, file}: E, SD (rows.SD), theta RMS (p2), file and day lists.
C = struct('E', {}, 'SD', {}, 'TH', {}, 'TS', {}, 'file', {}, 'day', {}, 'ok', {});
for k = 1:size(src, 1)
    [Z, cols, ok] = p2r_load(root, src{k, 2});
    if ~ok || ~any(strcmp(cols, src{k, 1})), C(k).ok = false; continue; end
    j = find(strcmp(cols, src{k, 1}), 1);
    C(k).ok = true;  C(k).file = {Z.rows.file}';  C(k).day = {Z.rows.day}';
    C(k).E = p2r_E(Z, cols, src(k, 1));
    C(k).SD = nan(numel(Z.rows), 1);
    if isfield(Z.rows, 'SD'), C(k).SD = arrayfun(@(r) r.SD(j), Z.rows(:)); end
    C(k).TH = p2r_p2(Z, cols, src(k, 1), 'theta_rms_stat_deg');
    C(k).TS = p2r_p2(Z, cols, src(k, 1), 'tilt_sat_frac');
end
end

function [fl, day] = oneset(C)
%ONESET  Segments finite in every given column (by file name), with their days.
fl = C(1).file(isfinite(C(1).E));
for k = 2:numel(C), fl = intersect(fl, C(k).file(isfinite(C(k).E))); end
[~, loc] = ismember(fl, C(1).file);
day = C(1).day(loc);
end

function s = qm(v, f)
%QM  Pooled quadratic mean, or "-" if any value is missing (not stored).
s = '-';
if ~isempty(v) && all(isfinite(v)), s = sprintf(f, sqrt(mean(v.^2))); end
end

function [Z, ok] = nominal_s40(root)
%NOMINAL_S40  The nominal level (m_p 0.5, L 1.0) = D2's rows on the S40 segments, as run_p2_gd6('TAB', ..., 'FromD2',
%  true) computes it (sec 39; that call saves no file). S40 list from the m_p 0.65 table (same registered S40 set).
Z = [];
[Zd, ~, okd] = p2r_load(root, 'gd6/d2_p2.mat');
[Zs, ~, oks] = p2r_load(root, 'gd6/tab_circle_mp065_p2.mat');
ok = okd && oks;
if ~ok, return; end
assert(strncmp(Zs.key.sha, '1db1de02532a3896', 16), 'make_p2_tables: the S40 list is not the registered S40 set.');
[tf, loc] = ismember({Zs.rows.file}, {Zd.rows.file});
assert(all(tf), 'make_p2_tables: %d S40 segment(s) missing from d2_p2.mat.', sum(~tf));
Z = struct('rows', Zd.rows(loc), 'key', struct('TauPred', Zd.key.TauPred, 'sha', Zs.key.sha));
end

%% ---------------------------------------------------------------------
function [E, day] = joinrows(Za, ca, wa, Zb, cb, wb)
%JOINROWS  Columns wa of file a and wb of file b on the segments present and finite in both (by file name).
Ea = p2r_E(Za, ca, wa);  Eb = p2r_E(Zb, cb, wb);
fa = {Za.rows.file};  fb = {Zb.rows.file};
[~, ia, ib] = intersect(fa, fb);
E = [Ea(ia, :), Eb(ib, :)];
day = {Za.rows(ia).day}';
Ka = p2r_E(Za, ca, ca);                                 % one set of file a (all its columns) on the shared segments
k = all(isfinite(E), 2) & all(isfinite(Ka(ia, :)), 2);
E = E(k, :);  day = day(k);
end

function U = segU(f)
M = load(f, 't_plant', 'w_plant');
U = norm(mean(M.w_plant(M.t_plant(:) >= 140, 1:2), 1));
end

function s = fmt(r)
s = sprintf('%+.2f %% (%.2f; [%+.2f, %+.2f]; %+.2f)', 100 * r.val, 100 * r.se, 100 * r.loo, 100 * r.med);
end

function s = tern(c, a, b)
if c, s = a; else, s = b; end
end
